import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar/Navbar";
import {Provider} from "./provider";
import CategoryNavbar from "@/app/components/navbar/CategoryNavbar";
import React from "react";
import AuthModals from "../utils/AuthModals"
import {getServerSession} from "next-auth";
import {CartProvider} from "@/app/contexts/CartContext";
import {Toaster} from "react-hot-toast";
import Footer from "@/app/components/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession();

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider session={session}>
            <CartProvider>
                <div className="min-h-screen">
                    <Navbar/>
                    <CategoryNavbar/>
                    <Toaster />
                    <div className="flex flex-wrap">
                        <main className="flex-1 p-4">
                            <AuthModals/>
                            {children}
                        </main>
                        <Footer />
                    </div>
                </div>
            </CartProvider>
        </Provider>
        </body>
        </html>
    );
}